[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.3.0"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"
"@uniswap-v3-periphery" = "1.4.4"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
